import importlib.metadata
import os

# -- CASM common configuration ---


# General information about the project.
project = "CASM"
copyright = "2026, CASM Developers"
author = "CASM Developers"

# -*- coding: utf-8 -*-
#
# CASM documentation build configuration file, created by
# sphinx-quickstart on Sat Sep 16 00:49:21 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

intersphinx_libcasm_packages = [
    ("global", "2.0"),
    ("xtal", "3"),
    ("composition", "2.0"),
    ("mapping", "3"),
    ("clexulator", "3"),
    ("configuration", "3"),
    ("monte", "3"),
    ("clexmonte", "3"),
]
intersphinx_casm_packages = [
    ("bset", "2.0"),
    ("tools", "2.0"),
    ("project", "2.0"),
]


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

autoclass_content = "both"
# autodoc_class_signature = "separated"
autosummary_generate = True
autosummary_imported_members = True
numpydoc_show_class_members = False
# autodoc_typehints = 'both'
autodoc_typehints_format = "short"
python_use_unqualified_type_names = True
autodoc_inherit_docstrings = False
add_module_names = True

intersphinx_mapping = {}

# if LIBCASM_LOCAL_PYDOCS env variable is set, create local docs
pydocs_path = os.environ.get("LIBCASM_LOCAL_PYDOCS", None)
for package, vers in intersphinx_libcasm_packages:
    if pydocs_path is None:
        url = (
            f"https://prisms-center.github.io/CASMcode_pydocs/libcasm/{package}/{vers}/"
        )
        inventory = None
    else:
        url = os.path.join(pydocs_path, f"{package}/{vers}/html")
        inventory = os.path.join(pydocs_path, f"{package}/{vers}/objects.inv")
    intersphinx_mapping[package] = (url, inventory)
for package, vers in intersphinx_casm_packages:
    if pydocs_path is None:
        url = f"https://prisms-center.github.io/CASMcode_pydocs/casm/{package}/{vers}/"
        inventory = None
    else:
        url = os.path.join(pydocs_path, f"{package}/{vers}/html")
        inventory = os.path.join(pydocs_path, f"{package}/{vers}/objects.inv")
    intersphinx_mapping[package] = (url, inventory)

print(intersphinx_mapping)

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.coverage",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",
    "sphinxarg.ext",
    # "sphinxcontrib.bibtex",
    "sphinxcontrib.email",
    "sphinx.ext.intersphinx",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinxext.opengraph",
    "numpydoc",
]

# OpenGraph meta tags — render a sensible preview when a docs page is shared
# on Twitter/X, LinkedIn, Bluesky, Mastodon, Slack, etc. Pairs with the
# manual share buttons in src/home/index.rst.
ogp_site_url = "https://bpuchala.github.io/CASMcode_pydocs/home/"
ogp_site_name = "CASM"
ogp_description_length = 200
# Set when a hero/social image is available. Should be a raster PNG/JPEG
# (most social platforms don't render SVG OG images).
ogp_image = "https://bpuchala.github.io/CASMcode_pydocs/home/_static/og_image.png"

# bibtex_bibfiles = ["refs.bib"]

# Napoleon settings
napoleon_google_docstring = False
napoleon_numpy_docstring = True
python_maximum_signature_line_length = 20

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {".rst": "restructuredtext"}

# The master toctree document.
master_doc = "index"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#


# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = [
    # Excluded from doc tree; stubs are generated via _generate_autosummary_stubs()
    # in setup() below, which avoids the 'referenced in multiple toctrees' warning.
    'reference/_stub_gen.rst',
]

# The name of the Pygments (syntax highlighting) style to use.
# pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Suppress specific warnings
suppress_warnings = [
    'docutils',
    'ref.duplicate',  # Suppresses duplicate explicit target name warnings
    'download.not_readable',
]

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"

# Add loading="lazy" to every <img>. Sphinx's html_image_loading wrapper was
# removed in 9.x; override the underlying docutils setting directly. Big win
# on the publications page (170 cards, ~5.5 MB of images otherwise eager-
# loaded); benign on other pages — browsers still eager-load above-the-fold
# images regardless of the attribute.
html_writer_settings = {"image_loading": "lazy"}

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

html_logo = "_static/small_logo.svg"
html_theme_options = {
    "logo": {
        "text": "CASM",
        "image_light": "_static/small_logo.svg",
        "image_dark": "_static/small_logo_dark.svg",
    },
    "pygments_light_style": "xcode",
    "pygments_dark_style": "lightbulb",
    "collapse_navigation": False,  # Prevents collapsing of navigation
    "navigation_depth": -1,        # Hides the sidebar by setting depth to -1
}
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = [
    "css/custom.css",
    "css/featured_random.css",
    "css/tom-select.bootstrap5.min.css",
    "css/publications_list.css",
]
html_js_files = [
    "js/pkg_nav_labels.js",
    "js/featured_random.js",
    "js/list.min.js",
    "js/tom-select.complete.min.js",
    "js/publications_list.js",
]
html_favicon = "_static/favicon-16x16.png"
html_show_sourcelink = False

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
# html_sidebars = {
#     '**': [
#         'about.html',
#         'navigation.html',
#         'relations.html',  # needs 'show_related': True theme option to display
#         'searchbox.html',
#         'donate.html',
#     ]
# }

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "CASMdoc"


# -- Per-module package/version annotation ------------------------------------

def _pkg_version(pkg):
    try:
        return importlib.metadata.version(pkg)
    except importlib.metadata.PackageNotFoundError:
        return "unknown"


_pypi_packages = [
    "libcasm-global",
    "libcasm-xtal",
    "libcasm-composition",
    "libcasm-mapping",
    "libcasm-clexulator",
    "libcasm-configuration",
    "libcasm-monte",
    "libcasm-clexmonte",
    "casm-bset",
    "casm-tools",
    "casm-project",
]

rst_prolog = "\n".join(
    f".. |version_{pkg.replace('-', '_')}| replace:: *v{_pkg_version(pkg)}*"
    for pkg in _pypi_packages
)


_module_to_pypi = {
    "libcasm.casmglobal": "libcasm-global",
    "libcasm.counter": "libcasm-global",
    "libcasm.xtal": "libcasm-xtal",
    "libcasm.composition": "libcasm-composition",
    "libcasm.mapping": "libcasm-mapping",
    "libcasm.clexulator": "libcasm-clexulator",
    "libcasm.clusterography": "libcasm-configuration",
    "libcasm.configuration": "libcasm-configuration",
    "libcasm.enumerate": "libcasm-configuration",
    "libcasm.group": "libcasm-configuration",
    "libcasm.irreps": "libcasm-configuration",
    "libcasm.local_configuration": "libcasm-configuration",
    "libcasm.occ_events": "libcasm-configuration",
    "libcasm.sym_info": "libcasm-configuration",
    "libcasm.monte": "libcasm-monte",
    "libcasm.clexmonte": "libcasm-clexmonte",
    "casm.bset": "casm-bset",
    "casm.tools": "casm-tools",
    "casm.project": "casm-project",
}


def _get_pypi_package(module_name):
    parts = module_name.split(".")
    for i in range(len(parts), 0, -1):
        prefix = ".".join(parts[:i])
        if prefix in _module_to_pypi:
            return _module_to_pypi[prefix]
    return None


def _source_read(app, docname, source):
    """Inject package/version line into autosummary stub pages and project structure pages."""
    if "_autosummary/" in docname:
        obj_name = docname.rsplit("_autosummary/", 1)[-1]
        pypi_pkg = _get_pypi_package(obj_name)
    elif "reference/project_structure/" in docname:
        pypi_pkg = "casm-project"
    else:
        return
    if pypi_pkg is None:
        return
    try:
        version = importlib.metadata.version(pypi_pkg)
    except importlib.metadata.PackageNotFoundError:
        version = "unknown"
    pypi_url = f"https://pypi.org/project/{pypi_pkg}/"
    pkg_line = f"*Package:* `{pypi_pkg} <{pypi_url}>`__ v{version}"
    lines = source[0].split("\n")
    # Insert after the first blank line (which follows the title underline)
    for i in range(2, len(lines)):
        if lines[i] == "":
            lines.insert(i + 1, "")
            lines.insert(i + 1, pkg_line)
            break
    source[0] = "\n".join(lines)


def _generate_autosummary_stubs(app):
    """Generate autosummary stubs from _stub_gen.rst without adding to toctree.

    The purpose of this is to allow constructing captioned toctrees in
    reference/packages_reference.rst so that the documentation of Python packages is
    grouped by distribution package. The captioned toctrees cannot generate the
    _autosummary stub files.

    _stub_gen.rst is excluded from the Sphinx document tree (via exclude_patterns)
    so its autosummary toctree never conflicts with the captioned toctrees in
    packages_reference.rst. We call generate_autosummary_docs directly to still
    produce the stub files on disk.

    Priority 400 ensures this runs before autosummary's process_generate_options
    (priority 500), so the top-level module stubs exist when autosummary recursively
    generates member stubs from the templates.
    """
    from sphinx.ext.autodoc._dynamic._mock import mock
    from sphinx.ext.autosummary import get_rst_suffix
    from sphinx.ext.autosummary.generate import generate_autosummary_docs

    suffix = get_rst_suffix(app)
    if suffix is None:
        return

    with mock(app.config.autosummary_mock_imports):
        generate_autosummary_docs(
            ['reference/_stub_gen.rst'],
            suffix=suffix,
            base_path=app.srcdir,
            app=app,
            imported_members=app.config.autosummary_imported_members,
            overwrite=app.config.autosummary_generate_overwrite,
            encoding=app.config.source_encoding,
        )


def setup(app):
    app.connect("source-read", _source_read)
    app.connect("builder-inited", _generate_autosummary_stubs, priority=400)

